//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 01:16:18 AM PDT 
//


package com.ge.dsp.pm.ext.entity.fieldtrigger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ge.dsp.pm.ext.entity.fieldtrigger package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FieldTriggerList_QNAME = new QName("http://dsp.ge.com/pm/ext/entity/fieldtrigger", "fieldTriggerList");
    private final static QName _FieldTrigger_QNAME = new QName("http://dsp.ge.com/pm/ext/entity/fieldtrigger", "fieldTrigger");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ge.dsp.pm.ext.entity.fieldtrigger
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FieldTrigger }
     * 
     */
    public FieldTrigger createFieldTrigger() {
        return new FieldTrigger();
    }

    /**
     * Create an instance of {@link FieldTriggerList }
     * 
     */
    public FieldTriggerList createFieldTriggerList() {
        return new FieldTriggerList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldTriggerList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dsp.ge.com/pm/ext/entity/fieldtrigger", name = "fieldTriggerList")
    public JAXBElement<FieldTriggerList> createFieldTriggerList(FieldTriggerList value) {
        return new JAXBElement<FieldTriggerList>(_FieldTriggerList_QNAME, FieldTriggerList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FieldTrigger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dsp.ge.com/pm/ext/entity/fieldtrigger", name = "fieldTrigger")
    public JAXBElement<FieldTrigger> createFieldTrigger(FieldTrigger value) {
        return new JAXBElement<FieldTrigger>(_FieldTrigger_QNAME, FieldTrigger.class, null, value);
    }

}
