package com.ge.dsp.pm.analytic.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2016-02-17T02:16:57.094-08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "analytic", 
                  wsdlLocation = "file:/predix/Documents/Anoop/downloads/predix-rmd-ref-app/ext-interface/ext-interface/src/main/resources/META-INF/schemas/pm/service/wsdl/runanalytic.wsdl",
                  targetNamespace = "http://dsp.ge.com/pm/analytic/service") 
public class Analytic_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dsp.ge.com/pm/analytic/service", "analytic");
    public final static QName AnalyticSOAP = new QName("http://dsp.ge.com/pm/analytic/service", "analyticSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/predix/Documents/Anoop/downloads/predix-rmd-ref-app/ext-interface/ext-interface/src/main/resources/META-INF/schemas/pm/service/wsdl/runanalytic.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Analytic_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/predix/Documents/Anoop/downloads/predix-rmd-ref-app/ext-interface/ext-interface/src/main/resources/META-INF/schemas/pm/service/wsdl/runanalytic.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Analytic_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Analytic_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Analytic_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Analytic_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Analytic_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Analytic_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Analytic
     */
    @WebEndpoint(name = "analyticSOAP")
    public Analytic getAnalyticSOAP() {
        return super.getPort(AnalyticSOAP, Analytic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Analytic
     */
    @WebEndpoint(name = "analyticSOAP")
    public Analytic getAnalyticSOAP(WebServiceFeature... features) {
        return super.getPort(AnalyticSOAP, Analytic.class, features);
    }

}
