//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.17 at 02:16:43 AM PST 
//


package com.ge.dsp.pm.ext.entity.timeselectionfilter;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for PredixEventTimeSelectionFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PredixEventTimeSelectionFilter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://dsp.ge.com/pm/ext/entity/timeselectionfilter}PredixTimeSelectionFilter">
 *       &lt;sequence>
 *         &lt;element name="eventTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eventRelativeTime" type="{http://dsp.ge.com/pm/ext/entity/timeselectionfilter}RelativeTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PredixEventTimeSelectionFilter", propOrder = {
    "eventTime",
    "eventRelativeTime"
})
public class PredixEventTimeSelectionFilter
    extends PredixTimeSelectionFilter
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTime;
    @XmlElement(required = true)
    protected RelativeTime eventRelativeTime;

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the eventRelativeTime property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeTime }
     *     
     */
    public RelativeTime getEventRelativeTime() {
        return eventRelativeTime;
    }

    /**
     * Sets the value of the eventRelativeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeTime }
     *     
     */
    public void setEventRelativeTime(RelativeTime value) {
        this.eventRelativeTime = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            XMLGregorianCalendar theEventTime;
            theEventTime = this.getEventTime();
            strategy.appendField(locator, this, "eventTime", buffer, theEventTime);
        }
        {
            RelativeTime theEventRelativeTime;
            theEventRelativeTime = this.getEventRelativeTime();
            strategy.appendField(locator, this, "eventRelativeTime", buffer, theEventRelativeTime);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PredixEventTimeSelectionFilter)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final PredixEventTimeSelectionFilter that = ((PredixEventTimeSelectionFilter) object);
        {
            XMLGregorianCalendar lhsEventTime;
            lhsEventTime = this.getEventTime();
            XMLGregorianCalendar rhsEventTime;
            rhsEventTime = that.getEventTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eventTime", lhsEventTime), LocatorUtils.property(thatLocator, "eventTime", rhsEventTime), lhsEventTime, rhsEventTime)) {
                return false;
            }
        }
        {
            RelativeTime lhsEventRelativeTime;
            lhsEventRelativeTime = this.getEventRelativeTime();
            RelativeTime rhsEventRelativeTime;
            rhsEventRelativeTime = that.getEventRelativeTime();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eventRelativeTime", lhsEventRelativeTime), LocatorUtils.property(thatLocator, "eventRelativeTime", rhsEventRelativeTime), lhsEventRelativeTime, rhsEventRelativeTime)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            XMLGregorianCalendar theEventTime;
            theEventTime = this.getEventTime();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eventTime", theEventTime), currentHashCode, theEventTime);
        }
        {
            RelativeTime theEventRelativeTime;
            theEventRelativeTime = this.getEventRelativeTime();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eventRelativeTime", theEventRelativeTime), currentHashCode, theEventRelativeTime);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
