//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 01:16:18 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dsp.ge.com/pm/ext/entity/source", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ge.dsp.pm.ext.entity.source;
